#!/bin/bash
# =============================================================================
# Pi Photo Slideshow — Automated Setup Script
# https://github.com/glenmo/pi-photo-slideshow
#
# Tested on: Raspberry Pi 3 & 5, Raspberry Pi OS (Debian Bookworm)
# Run as your normal user (not root) — sudo is used internally where needed
# =============================================================================

set -e

# --- Colour output helpers ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()    { echo -e "${CYAN}[INFO]${NC}  $1"; }
success() { echo -e "${GREEN}[OK]${NC}    $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

echo ""
echo -e "${CYAN}======================================${NC}"
echo -e "${CYAN}  Pi Photo Slideshow — Setup Script   ${NC}"
echo -e "${CYAN}======================================${NC}"
echo ""

# =============================================================================
# Configuration — derived from hostname automatically
# =============================================================================
HOSTNAME="$(hostname)"
DOMAIN="${HOSTNAME}.local"
DOCROOT="/var/www/${DOMAIN}"
PHOTOS_DIR="${DOCROOT}/photos"
OUTPUT_JSON="${DOCROOT}/photos.json"
VHOST_CONF="/etc/apache2/sites-available/${DOMAIN}.conf"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
USER="$(whoami)"
CONFIG_FILE="${HOME}/.slideshow_config"

info "User:          ${USER}"
info "Hostname:      ${HOSTNAME}"
info "Slideshow URL: http://${DOMAIN}/"
info "Document root: ${DOCROOT}"
info "Photos folder: ${PHOTOS_DIR}"
echo ""

# =============================================================================
# 1. Write config file so scan_photos.py knows the correct paths
# =============================================================================
info "Writing config to ${CONFIG_FILE}..."
cat > "${CONFIG_FILE}" << CONFIG
# Pi Photo Slideshow config — generated by setup.sh
PHOTO_DIR=${PHOTOS_DIR}
OUTPUT=${OUTPUT_JSON}
CONFIG
success "Config written."
echo ""

# =============================================================================
# 2. System update and package install
# =============================================================================
info "Updating package lists..."
sudo apt-get update -q

info "Installing Apache2, Python3, and Samba..."
sudo apt-get install -y -q apache2 python3 samba

success "Packages installed."
echo ""

# =============================================================================
# 3. Apache2 virtual host setup
# =============================================================================
info "Creating document root at ${DOCROOT}..."
sudo mkdir -p "${PHOTOS_DIR}"
sudo chown -R "${USER}:www-data" "${DOCROOT}"
sudo chmod -R 775 "${DOCROOT}"

info "Writing Apache2 virtual host config..."
sudo tee "${VHOST_CONF}" > /dev/null << APACHECONF
<VirtualHost *:80>
    ServerName ${DOMAIN}
    ServerAlias www.${DOMAIN}
    DocumentRoot ${DOCROOT}
    <Directory ${DOCROOT}>
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog \${APACHE_LOG_DIR}/${DOMAIN}-error.log
    CustomLog \${APACHE_LOG_DIR}/${DOMAIN}-access.log combined
</VirtualHost>
APACHECONF

info "Enabling virtual host..."
sudo a2ensite "${DOMAIN}.conf" > /dev/null 2>&1
sudo systemctl reload apache2

success "Apache2 configured at http://${DOMAIN}/"
echo ""

# =============================================================================
# 4. Deploy slideshow files
# =============================================================================
info "Deploying index.html to document root..."
if [ -f "${SCRIPT_DIR}/index.html" ]; then
    sudo cp "${SCRIPT_DIR}/index.html" "${DOCROOT}/index.html"
    sudo chown "${USER}:www-data" "${DOCROOT}/index.html"
    success "index.html deployed."
else
    error "index.html not found in ${SCRIPT_DIR}. Run this script from inside the cloned repo folder."
fi

info "Installing scan_photos.py to home directory..."
if [ -f "${SCRIPT_DIR}/scan_photos.py" ]; then
    cp "${SCRIPT_DIR}/scan_photos.py" "${HOME}/scan_photos.py"
    chmod +x "${HOME}/scan_photos.py"
    success "scan_photos.py installed to ${HOME}/scan_photos.py"
else
    error "scan_photos.py not found in ${SCRIPT_DIR}. Run this script from inside the cloned repo folder."
fi

echo ""

# =============================================================================
# 5. Run scanner once to create photos.json
# =============================================================================
info "Running photo scanner..."
python3 "${HOME}/scan_photos.py"
success "photos.json created."
echo ""

# =============================================================================
# 6. Cron job
# =============================================================================
info "Setting up cron job (runs every minute)..."
CRON_JOB="* * * * * python3 ${HOME}/scan_photos.py"
( crontab -l 2>/dev/null | grep -qF "scan_photos.py" ) \
    && warn "Cron job already exists, skipping." \
    || ( crontab -l 2>/dev/null; echo "${CRON_JOB}" ) | crontab -
success "Cron job set."
echo ""

# =============================================================================
# 7. Samba share
# =============================================================================
info "Configuring Samba share for photos folder..."

if sudo grep -q "\[photos\]" /etc/samba/smb.conf 2>/dev/null; then
    warn "Samba [photos] share already exists, skipping."
else
    sudo tee -a /etc/samba/smb.conf > /dev/null << SAMBACONF

[photos]
   path = ${PHOTOS_DIR}
   browseable = yes
   read only = no
   guest ok = no
   create mask = 0644
   directory mask = 0755
   force user = ${USER}
SAMBACONF
    sudo systemctl restart smbd
    success "Samba share configured."
fi

echo ""

# =============================================================================
# 8. Kiosk autostart
# =============================================================================
# Detect correct chromium binary name
CHROMIUM_BIN=""
if command -v chromium-browser &> /dev/null; then
    CHROMIUM_BIN="chromium-browser"
elif command -v chromium &> /dev/null; then
    CHROMIUM_BIN="chromium"
else
    warn "Chromium not found — kiosk mode will not be configured. Install with: sudo apt install chromium"
fi

info "Setting up Chromium kiosk mode on boot (using: ${CHROMIUM_BIN})..."
AUTOSTART_DIR="${HOME}/.config/lxsession/LXDE-pi"
AUTOSTART_FILE="${AUTOSTART_DIR}/autostart"
mkdir -p "${AUTOSTART_DIR}"

if [ -z "${CHROMIUM_BIN}" ]; then
    warn "Skipping kiosk autostart — chromium not installed."
elif grep -q "chromium.*--kiosk" "${AUTOSTART_FILE}" 2>/dev/null; then
    warn "Kiosk autostart already configured, skipping."
else
    cat >> "${AUTOSTART_FILE}" << AUTOSTART

@xset s off
@xset -dpms
@xset s noblank
@${CHROMIUM_BIN} --kiosk --incognito --disable-restore-session-state http://${DOMAIN}
AUTOSTART
    success "Kiosk autostart configured for http://${DOMAIN}/ using ${CHROMIUM_BIN}"
fi

echo ""

# =============================================================================
# 9. GPU memory tweak (helps Pi 3 render smoothly)
# =============================================================================
info "Checking GPU memory setting..."
CONFIG_FILE_BOOT="/boot/firmware/config.txt"
[ -f "${CONFIG_FILE_BOOT}" ] || CONFIG_FILE_BOOT="/boot/config.txt"

if grep -q "gpu_mem" "${CONFIG_FILE_BOOT}" 2>/dev/null; then
    warn "gpu_mem already set in ${CONFIG_FILE_BOOT}, skipping."
else
    echo "gpu_mem=128" | sudo tee -a "${CONFIG_FILE_BOOT}" > /dev/null
    success "Set gpu_mem=128 for smoother display rendering."
fi

echo ""

# =============================================================================
# Done
# =============================================================================
echo -e "${GREEN}======================================${NC}"
echo -e "${GREEN}  Setup complete!                     ${NC}"
echo -e "${GREEN}======================================${NC}"
echo ""
echo -e "  Slideshow URL : ${CYAN}http://${DOMAIN}/${NC}"
echo -e "  Photos folder : ${CYAN}${PHOTOS_DIR}${NC}"
echo -e "  Add photos via: ${CYAN}scp photo.jpg ${USER}@${DOMAIN}:${PHOTOS_DIR}/${NC}"
echo ""
echo -e "  ${YELLOW}Next steps:${NC}"
echo -e "  1. Set Samba password : ${YELLOW}sudo smbpasswd -a ${USER}${NC}"
echo -e "  2. Add photos to      : ${YELLOW}${PHOTOS_DIR}${NC}"
echo -e "  3. Reboot into kiosk  : ${YELLOW}sudo reboot${NC}"
echo ""
